In [1]:
import numpy as np

In [2]:
v1 = np.array([-1, 2, -7, 9])
v2 = np.array([2, 8, 2, -1])
print(np.dot(v1, v2))

-9


In [3]:
A = np.array([
    [1, 1],
    [1, 2]
])
G = np.dot(A.T, A)
print(G)

[[2 3]
 [3 5]]


In [4]:
A = np.array([
    [1, 2],
    [3, 7]
])
print(np.linalg.inv(A))

[[ 7. -2.]
 [-3.  1.]]


In [5]:
v1 = np.array([2, 10, -2])
v2 = np.array([3, 2, -2])
v3 = np.array([8, 14, -6])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2


In [8]:
A = np.array([
    [1, 1],
    [1, 2],
    [1, 1]
])
w = np.array([1, 1]).T
b = np.dot(A, w)
print(b)

[2 3 2]
