In [2]:
import numpy as np

In [3]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [9]:
incomes = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
incomes

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [10]:
consumptions = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
consumptions

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [11]:
0.87 * incomes

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [12]:
0.87 * incomes - consumptions

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])