In [9]:
import numpy as np
import pandas as pd

In [3]:
arr1 = np.array([120, 150, 190])
arr2 = np.array([130, 130, 130])
arr3 = np.array([2, 3, 2.5])
w = 72
arr1 + arr2 + (w * arr3)

array([394., 496., 500.])

In [4]:
2 * np.array([4, 5]) + (-3) * np.array([2, 1]) + 5 * np.array([1, 0])

array([7, 7])

In [6]:
-(200 * np.array([3, 4, 5, 9]) - 400 * np.array([1, 5, 3, 6]))

array([-200, 1200,  200,  600])

In [7]:
np.dot(np.array([4, 5, -1]), np.array([2, 0, 1]))

np.int64(7)

In [8]:
print(np.dot(np.array([4, 2, -1]), np.array([2, 0, 1])))
print(np.dot(np.array([4, 5, -1]), np.array([0, 0, 0])))
print(np.dot(np.array([4, -1]), np.array([-1, 4])))
print(np.dot(np.array([4, -1]), np.array([1, 4])))

7
0
-8
0


In [10]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [11]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [12]:
Hut_Paradise_values

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [15]:
Hut_Paradise_values[:, 1] - Hut_Paradise_values[:, -1]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [17]:
demo_counts = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
(Hut_Paradise_values[:, -2] * demo_counts).sum()

np.int64(1348)

In [19]:
u = np.array([3,0,1,1,1])
v = np.array([0,1,0,2,-2])
w = np.array([1,-4,-1,0,-2])
omega1 = 2
omega2 = -3
vec = omega1 * v + omega2 * w
vec

array([-3, 14,  3,  4,  2])

In [20]:
np.dot(u, vec)

np.int64(0)