In [1]:
import numpy as np

In [4]:
a = np.array([4, 1, 0])
b = np.array([-1, 4, 0])
c = np.array([0, 0, 1])
print(f"dot a*b is {np.dot(a, b)}")
print(f"dot a*c is {np.dot(a, c)}")
print(f"dot b*c is {np.dot(b, c)}")

dot a*b is 0
dot a*c is 0
dot b*c is 0


In [5]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
print(np.linalg.inv(A))

[[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]


In [11]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
A = np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(A))

4


In [12]:
G = np.dot(A.T, A)
print(G)

[[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


In [13]:
print(round(np.linalg.det(G)))

3716648


In [15]:
print(np.linalg.inv(G))

[[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
