In [6]:
import numpy as np
import pandas as pd

In [3]:
A = np.array([
    [1, -1, 2, 4, 0],
    [8, 2, 0, 5, 3],
    [0, 1, 2, 1, 2]
])

B = np.array([
    [1, 0, 1, 0],
    [0, 0, 2, -1],
    [1, 0, 1, 1],
    [0, 1, 1, 1],
    [1, 1, 0, -1]
])

print(np.dot(A, B))

[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]


In [10]:
vec1 = np.array([
    [1],
    [3]
])
vec2 = np.array([[-3, 1]])
print(np.dot(vec1, vec2))

[[-3  1]
 [-9  3]]


In [11]:
A = np.array([
    [2, 0],
    [0, 2]
])
B = np.array([
    [1, 1],
    [4, 5]
])
print(np.dot(A, B))

[[ 2  2]
 [ 8 10]]


In [12]:
X = np.array([
    [1, 2, 1],
    [1, -1, 2]
])
G = np.dot(X.T, X)
print(G)

[[2 1 3]
 [1 5 0]
 [3 0 5]]


In [2]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
print(np.dot(x, A.T))

[26 30]


In [3]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
print(np.dot(B, A))

[[  2   9  11  14]
 [  8 -10 -14 -11]]


In [5]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x, y, z])
G = np.dot(A.T, A)
print(G)

[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


In [7]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [23]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
count_matrix = Count_DF.values
price_matrix = Price_DF.values
print((price_matrix * count_matrix * com).sum(axis=1))


[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [25]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
print(A)
print(np.linalg.inv(A))
print(A * np.linalg.inv(A))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
[[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]]


In [27]:
A = np.array([
    [1, 2],
    [2, 5]
])
print(np.linalg.inv(A))

[[ 5. -2.]
 [-2.  1.]]


In [28]:
A = np.array([
    [2, 0, 0],
    [0, 4, 0],
    [0, 0, 5]
])
print(np.eye(3) * np.linalg.inv(A))

[[0.5  0.   0.  ]
 [0.   0.25 0.  ]
 [0.   0.   0.2 ]]


In [31]:
A = np.array([
    [1, 2],
    [1, 1]
])
B = np.array([
    [5, -2],
    [-1, 4]
])
print(round(np.linalg.det(A)))
print(round(np.linalg.det(B)))
print(round(np.linalg.det(A + B)))

-1
18
30


In [34]:
A = np.array([
    [2, 0, 0],
    [0, 1, 0],
    [0, 0, 4]
])
print(round(np.linalg.det(A)))
print(round(np.linalg.det(np.linalg.inv(A)), 3))

8
0.125
